#!/usr/bin/env node

/**
 * TWS Backend Quick Fix Script
 * This script addresses the critical issues found in the debugging analysis
 */

const { spawn, exec } = require('child_process');
const fs = require('fs');
const path = require('path');

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m'
};

class TWSQuickFix {
  constructor() {
    this.fixes = [];
    this.results = [];
  }

  log(message, color = 'reset') {
    console.log(`${colors[color]}${message}${colors.reset}`);
  }

  logSuccess(message) {
    this.log(`✅ ${message}`, 'green');
  }

  logWarning(message) {
    this.log(`⚠️  ${message}`, 'yellow');
  }

  logError(message) {
    this.log(`❌ ${message}`, 'red');
  }

  logInfo(message) {
    this.log(`ℹ️  ${message}`, 'blue');
  }

  logSection(title) {
    console.log('\n' + '='.repeat(60));
    this.log(`🔧 ${title}`, 'cyan');
    console.log('='.repeat(60));
  }

  // Create environment file
  createEnvironmentFile() {
    this.logSection('Creating Environment Configuration');
    
    const envContent = `# TWS Backend Environment Configuration
# Generated by Quick Fix Script

# Server Configuration
NODE_ENV=development
PORT=4000

# Database Configuration
MONGO_URI=mongodb://localhost:27017/tws-dev

# JWT Configuration
JWT_SECRET=your-super-secret-jwt-key-change-in-production-64-chars-minimum
JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-in-production-64-chars-minimum
JWT_EXPIRES_IN=24h
JWT_REFRESH_EXPIRES_IN=7d

# Encryption Configuration
ENCRYPTION_MASTER_KEY=your-256-bit-encryption-master-key-here-32-chars

# Redis Configuration
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=0
REDIS_DISABLED=false
BULLMQ_DISABLED=false

# CORS Configuration
CORS_ORIGIN=http://localhost:3000
SOCKET_CORS_ORIGIN=http://localhost:3000

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# File Upload
MAX_FILE_SIZE=10mb
UPLOAD_PATH=./uploads

# Email Configuration (Optional)
EMAIL_HOST=
EMAIL_PORT=587
EMAIL_USER=
EMAIL_PASS=
EMAIL_FROM=noreply@tws.com

# AWS Configuration (Optional)
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=us-east-1
AWS_S3_BUCKET=

# Firebase Configuration (Optional)
FIREBASE_API_KEY=
FIREBASE_AUTH_DOMAIN=
FIREBASE_PROJECT_ID=
FIREBASE_STORAGE_BUCKET=
FIREBASE_MESSAGING_SENDER_ID=
FIREBASE_APP_ID=

# Monitoring
SENTRY_DSN=
LOG_LEVEL=info

# Feature Flags
ENABLE_BIOMETRIC=false
ENABLE_ANALYTICS=true
ENABLE_NOTIFICATIONS=true
ENABLE_FILE_UPLOAD=true
ENABLE_EMAIL_SERVICE=false
ENABLE_STRIPE=false
ENABLE_AWS=false
`;

    try {
      fs.writeFileSync('.env', envContent);
      this.logSuccess('Environment file created: .env');
      this.fixes.push('Environment file created');
      return true;
    } catch (error) {
      this.logError(`Failed to create environment file: ${error.message}`);
      return false;
    }
  }

  // Check if MongoDB is running
  async checkMongoDB() {
    this.logSection('Checking MongoDB Status');
    
    return new Promise((resolve) => {
      exec('mongosh --eval "db.runCommand({ping: 1})" --quiet', (error, stdout, stderr) => {
        if (error) {
          this.logError('MongoDB is not running or not accessible');
          this.logInfo('To start MongoDB:');
          this.logInfo('  Windows: net start MongoDB');
          this.logInfo('  Docker: docker run -d -p 27017:27017 --name mongodb mongo:7.0');
          this.logInfo('  Manual: mongod --dbpath /path/to/data');
          resolve(false);
        } else {
          this.logSuccess('MongoDB is running and accessible');
          resolve(true);
        }
      });
    });
  }

  // Check if Redis is running
  async checkRedis() {
    this.logSection('Checking Redis Status');
    
    return new Promise((resolve) => {
      exec('redis-cli ping', (error, stdout, stderr) => {
        if (error) {
          this.logWarning('Redis is not running or not accessible');
          this.logInfo('To start Redis:');
          this.logInfo('  Windows: redis-server');
          this.logInfo('  Docker: docker run -d -p 6379:6379 --name redis redis:7-alpine');
          resolve(false);
        } else {
          this.logSuccess('Redis is running and accessible');
          resolve(true);
        }
      });
    });
  }

  // Test server startup
  async testServerStartup() {
    this.logSection('Testing Server Startup');
    
    return new Promise((resolve) => {
      const testScript = `
        try {
          const { app, server } = require('./src/app.js');
          console.log('✅ Server app loaded successfully');
          process.exit(0);
        } catch (error) {
          console.error('❌ Server startup failed:', error.message);
          process.exit(1);
        }
      `;
      
      const child = spawn('node', ['-e', testScript], {
        stdio: 'pipe',
        cwd: process.cwd()
      });
      
      let output = '';
      child.stdout.on('data', (data) => {
        output += data.toString();
      });
      
      child.stderr.on('data', (data) => {
        output += data.toString();
      });
      
      child.on('close', (code) => {
        if (code === 0) {
          this.logSuccess('Server startup test passed');
          resolve(true);
        } else {
          this.logError('Server startup test failed');
          this.logInfo('Output:', output);
          resolve(false);
        }
      });
    });
  }

  // Create startup scripts
  createStartupScripts() {
    this.logSection('Creating Startup Scripts');
    
    // Windows batch script
    const windowsScript = `@echo off
echo Starting TWS Backend Services...

REM Start MongoDB (if not running)
net start MongoDB 2>nul || echo MongoDB already running or not installed

REM Start Redis (if not running)
redis-server --daemonize yes 2>nul || echo Redis already running or not installed

REM Start Backend
echo Starting Backend on port 4000...
start "TWS Backend" cmd /k "cd /d %~dp0 && npm start"

REM Start Admin Dashboard
echo Starting Admin Dashboard on port 3001...
start "TWS Admin Dashboard" cmd /k "cd /d %~dp0\\..\\admin-dashboard && npm start"

echo All services started!
pause
`;

    // Linux/Mac shell script
    const unixScript = `#!/bin/bash
echo "Starting TWS Backend Services..."

# Start MongoDB (if not running)
if ! pgrep -x "mongod" > /dev/null; then
    echo "Starting MongoDB..."
    mongod --fork --logpath /var/log/mongodb.log
fi

# Start Redis (if not running)
if ! pgrep -x "redis-server" > /dev/null; then
    echo "Starting Redis..."
    redis-server --daemonize yes
fi

# Start Backend
echo "Starting Backend on port 4000..."
cd "$(dirname "$0")"
npm start &

# Start Admin Dashboard
echo "Starting Admin Dashboard on port 3001..."
cd "../admin-dashboard"
npm start &

echo "All services started!"
`;

    try {
      fs.writeFileSync('start-services.bat', windowsScript);
      fs.writeFileSync('start-services.sh', unixScript);
      
      // Make shell script executable
      if (process.platform !== 'win32') {
        exec('chmod +x start-services.sh');
      }
      
      this.logSuccess('Startup scripts created:');
      this.logInfo('  Windows: start-services.bat');
      this.logInfo('  Unix/Linux: start-services.sh');
      this.fixes.push('Startup scripts created');
      return true;
    } catch (error) {
      this.logError(`Failed to create startup scripts: ${error.message}`);
      return false;
    }
  }

  // Create health check script
  createHealthCheckScript() {
    this.logSection('Creating Health Check Script');
    
    const healthCheckScript = `#!/usr/bin/env node

const http = require('http');

const services = [
  { name: 'Frontend', url: 'http://localhost:3000' },
  { name: 'Backend', url: 'http://localhost:5000/health' },
  { name: 'Admin Dashboard', url: 'http://localhost:3001' },
  { name: 'Backend Alt', url: 'http://localhost:4000/health' }
];

async function checkService(service) {
  return new Promise((resolve) => {
    const req = http.get(service.url, (res) => {
      resolve({ name: service.name, status: res.statusCode, healthy: res.statusCode === 200 });
    });
    
    req.on('error', () => {
      resolve({ name: service.name, status: 'ERROR', healthy: false });
    });
    
    req.setTimeout(5000, () => {
      req.destroy();
      resolve({ name: service.name, status: 'TIMEOUT', healthy: false });
    });
  });
}

async function checkAllServices() {
  console.log('🔍 Checking TWS Services Health...\\n');
  
  const results = await Promise.all(services.map(checkService));
  
  results.forEach(result => {
    const status = result.healthy ? '✅' : '❌';
    console.log(\`\${status} \${result.name}: \${result.status}\`);
  });
  
  const healthyCount = results.filter(r => r.healthy).length;
  const totalCount = results.length;
  
  console.log(\`\\n📊 Health Summary: \${healthyCount}/\${totalCount} services healthy\`);
  
  if (healthyCount === totalCount) {
    console.log('🎉 All services are healthy!');
    process.exit(0);
  } else {
    console.log('⚠️ Some services need attention.');
    process.exit(1);
  }
}

checkAllServices();
`;

    try {
      fs.writeFileSync('scripts/health-check.js', healthCheckScript);
      this.logSuccess('Health check script created: scripts/health-check.js');
      this.fixes.push('Health check script created');
      return true;
    } catch (error) {
      this.logError(`Failed to create health check script: ${error.message}`);
      return false;
    }
  }

  // Main fix function
  async run() {
    this.log('🚀 Starting TWS Backend Quick Fix', 'bright');
    this.log('=' .repeat(60), 'cyan');
    
    try {
      // Create environment file
      this.createEnvironmentFile();
      
      // Check MongoDB
      const mongoRunning = await this.checkMongoDB();
      
      // Check Redis
      const redisRunning = await this.checkRedis();
      
      // Test server startup
      const serverTest = await this.testServerStartup();
      
      // Create startup scripts
      this.createStartupScripts();
      
      // Create health check script
      this.createHealthCheckScript();
      
      // Summary
      this.logSection('Quick Fix Summary');
      
      this.logInfo('Fixes Applied:');
      this.fixes.forEach(fix => {
        this.logInfo(`  ✅ ${fix}`);
      });
      
      this.logInfo('\\nNext Steps:');
      this.logInfo('1. Start MongoDB service');
      this.logInfo('2. Start Redis service (optional)');
      this.logInfo('3. Run: npm start');
      this.logInfo('4. Run: cd ../admin-dashboard && npm start');
      this.logInfo('5. Test with: node scripts/health-check.js');
      
      if (!mongoRunning) {
        this.logWarning('⚠️ MongoDB needs to be started before running the server');
      }
      
      if (!redisRunning) {
        this.logWarning('⚠️ Redis is optional but recommended for full functionality');
      }
      
      this.logSuccess('🎉 Quick fix completed!');
      
    } catch (error) {
      this.logError(`Quick fix failed: ${error.message}`);
      console.error(error);
    }
  }
}

// Run the quick fix if this script is executed directly
if (require.main === module) {
  const quickFix = new TWSQuickFix();
  quickFix.run();
}

module.exports = TWSQuickFix;
