# Script to delete redundant markdown files
# Review MARKDOWN_CLEANUP_PLAN.md before running

$filesToDelete = @(
    # Redundant "COMPLETE" Status Files
    "AUTH_CLEANUP_COMPLETE.md",
    "FINAL_IMPLEMENTATION_COMPLETE.md",
    "FINAL_IMPROVEMENTS_COMPLETE.md",
    "FINAL_INTEGRATION_COMPLETE.md",
    "IMPLEMENTATION_COMPLETE.md",
    "REMAINING_STEPS_COMPLETE.md",
    "COMPLETE_BACKEND_INTEGRATION_SUMMARY.md",
    "CRITICAL_FINDING_3_IMPLEMENTATION_COMPLETE.md",
    "CRITICAL_FINDING_4_IMPLEMENTATION_COMPLETE.md",
    "EDUCATION_ERP_COMPLETION_SUMMARY.md",
    "EDUCATION_ERP_SETUP_COMPLETE.md",
    "FINAL_FINANCE_INTEGRATION_COMPLETE.md",
    "FINANCE_MIGRATION_COMPLETE.md",
    "FINANCE_MODULES_COMPLETE.md",
    "GANTT_CHART_IMPLEMENTATION_COMPLETE.md",
    "HIGH_PRIORITY_SECURITY_FIXES_COMPLETE.md",
    "HRM_COMPLETE_BACKEND_INTEGRATION.md",
    "HRM_ENHANCEMENTS_COMPLETE.md",
    "HRM_FINAL_COMPLETION_SUMMARY.md",
    "NUCLEUS_ALL_CRITICAL_FIXES_COMPLETE.md",
    "NUCLEUS_PHASE2_IMPLEMENTATION_COMPLETE.md",
    "NUCLEUS_PHASE3_COMPLETE.md",
    "NUCLEUS_PHASE4_UX_ENHANCEMENTS_COMPLETE.md",
    "NUCLEUS_PHASE5_NAVIGATION_COMPLETE.md",
    "NUCLEUS_UPGRADE_COMPLETE_SUMMARY.md",
    "PROJECT_INTEGRATION_IMPLEMENTATION_COMPLETE.md",
    "PROJECTS_FIXES_COMPLETE.md",
    "SOFTWARE_HOUSE_SIGNUP_INTEGRATION_COMPLETE.md",
    "TENANT_PROJECTS_BACKEND_COMPLETE.md",
    "TENANT_PROJECTS_BACKEND_INTEGRATION_COMPLETE.md",
    "TENANT_PROJECTS_COMPLETE_DELIVERY.md",
    "TENANT_PROJECTS_MODALS_COMPLETE.md",
    "TENANT_PROJECTS_UTILITIES_COMPLETE.md",
    
    # Duplicate Summary Files
    "NUCLEUS_FINAL_IMPLEMENTATION_SUMMARY.md",
    "NUCLEUS_COMPLETE_IMPLEMENTATION_SUMMARY.md",
    "NUCLEUS_UPGRADE_IMPLEMENTATION_SUMMARY.md",
    "NUCLEUS_CRITICAL_FIXES_IMPLEMENTATION_SUMMARY.md",
    "TENANT_PROJECTS_COMPLETION_SUMMARY.md",
    "TENANT_PROJECTS_FINAL_SUMMARY.md",
    "TENANT_MODULES_FINAL_SUMMARY.md",
    "HRM_REBUILD_SUMMARY.md",
    "HRM_REBUILD_ACCOMPLISHMENTS.md",
    "HRM_REBUILD_FINAL_REPORT.md",
    "FINANCE_REBUILD_SUMMARY.md",
    "DEPARTMENT_ARCHITECTURE_IMPLEMENTATION_SUMMARY.md",
    
    # Old Status Files
    "IMPLEMENTATION_STATUS.md",
    "PROGRESS_UPDATE.md",
    "FINANCE_MODULE_INTEGRATION_STATUS.md",
    "HRM_BACKEND_INTEGRATION_STATUS.md",
    "PROJECTS_MODULE_INTEGRATION_STATUS.md",
    "TENANT_MODULES_COMPLETE_STATUS.md",
    "TENANT_PROJECTS_FINAL_STATUS.md",
    "NUCLEUS_FINAL_IMPLEMENTATION_STATUS.md",
    
    # Temporary Debugging/Fix Files
    "AUTHENTICATION_FIX.md",
    "TOKEN_ERROR_FIX.md",
    "FINANCE_ROUTES_404_FIX.md",
    "ROUTE_DEBUGGING.md",
    "FIXES_IMPLEMENTED.md",
    "BACKEND_FINANCE_ROUTES_COMPLETE.md",
    "HRM_BACKEND_INTEGRATION_FIXES.md",
    "EDUCATION_ERP_FIX_ACTION_PLAN.md",
    
    # Old Implementation Plans
    "TENANT_PROJECTS_BACKEND_NEXT_STEPS.md",
    "TENANT_PROJECTS_NEXT_STEPS.md",
    "EDUCATION_ERP_NEXT_STEPS.md",
    
    # Redundant Documentation
    "PROJECTS_FIXES_SUMMARY.md",
    "CSRF_REMOVAL_SUMMARY.md",
    "MESSAGING_REMOVAL_SUMMARY.md",
    "AUTH_SYSTEM_REFACTOR_SUMMARY.md",
    
    # Old Checklists
    "EDUCATION_ERP_FINAL_CHECKLIST.md",
    "EDUCATION_ERP_READY_FOR_DEPLOYMENT.md",
    "HRM_VERIFICATION_CHECKLIST.md",
    
    # Prompt/Design Files
    "HEALTHCARE_ERP_CSS_DESIGN_SYSTEM_PROMPT.md",
    "HEALTHCARE_ERP_LANDING_PAGE_PROMPT.md",
    "SIGNUP_FORM_INDUSTRY_SPECIFIC_PROPOSAL.md",
    
    # Testing Files (if outdated)
    "TENANT_PROJECTS_TEST_RESULTS.md",
    
    # Redundant Implementation Guides
    "TENANT_PROJECTS_BACKEND_IMPLEMENTATION.md",
    "FR2_SELF_SERVE_SIGNUP_IMPLEMENTATION.md",
    "INDUSTRY_SPECIFIC_SIGNUP_IMPLEMENTATION.md",
    "EMAIL_VALIDATION_IMPLEMENTATION.md",
    
    # Other Redundant Files
    "PROJECT_STRUCTURE_INDEX.md",
    "SRS_DOCUMENT_TEMPLATE.md",
    "USE_CASE_DIAGRAM_README.md",
    "USE_CASE_DIAGRAMS_ANALYSIS_REPORT.md",
    "TWS_USE_CASE_DIAGRAM_COMPACT.md",
    "TWS_USE_CASE_DIAGRAM_UML.md",
    "PROJECT_MANAGEMENT_ROUTES_VERIFICATION_REPORT.md",
    "PROJECT_MANAGEMENT_ACTIVITY_RELATIONSHIPS.md",
    "TENANT_SOFTWARE_HOUSE_FINANCE_COMPARISON.md",
    "FINANCE_MOVED_TO_SOFTWARE_HOUSE.md",
    "HEALTHCARE_ERP_REMEDIATION_ACTION_PLAN.md"
)

Write-Host "Files to be deleted: $($filesToDelete.Count)" -ForegroundColor Yellow
Write-Host "`nReview the list above. Press any key to continue with deletion, or Ctrl+C to cancel..." -ForegroundColor Cyan
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

$deletedCount = 0
$notFoundCount = 0

foreach ($file in $filesToDelete) {
    if (Test-Path $file) {
        Remove-Item $file -Force
        Write-Host "Deleted: $file" -ForegroundColor Green
        $deletedCount++
    } else {
        Write-Host "Not found: $file" -ForegroundColor Gray
        $notFoundCount++
    }
}

Write-Host "`nDeletion complete!" -ForegroundColor Green
Write-Host "Deleted: $deletedCount files" -ForegroundColor Green
Write-Host "Not found: $notFoundCount files" -ForegroundColor Gray

